name: PHP

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: test
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - uses: actions/checkout@v2

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: pdo, pdo_mysql, pdo_sqlite, sqlite3
        coverage: xdebug

    - name: Install dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist

    - name: Copy .env.example to .env
      run: cp .env.example .env

    - name: Generate key
      run: php artisan key:generate

    - name: Create SQLite database
      run: |
        touch database/database.sqlite
        chmod 666 database/database.sqlite

    - name: Execute tests (Unit and Feature tests)
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
        DB_FOREIGN_KEYS: true
      run: vendor/bin/phpunit

    - name: Execute tests (Unit tests)
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
        DB_FOREIGN_KEYS: true
      run: vendor/bin/phpunit --testsuite Unit

    - name: Execute tests (Feature tests)
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
        DB_FOREIGN_KEYS: true
      run: vendor/bin/phpunit --testsuite Feature 